### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by olgakozoriz** [NodeArt/Angular-Firebase-Sortable-Table#1]
Could you please provide less complicated example or how-to?

**Comment by IvanProdaiko94** [comment]
Okey. What do you stuck with?

**Comment by olgakozoriz** [comment]
Like how to show simple collection in a table?

**Comment by IvanProdaiko94** [comment]
Keep in touch with [version 2.0.0](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/tree/2.0.0), docs will be written soon
