### ISSUE TITLE
Error if firebase value is not an Object

### ISSUE THREAD

**Issue by iatalmid** [NodeArt/Angular-Firebase-Sortable-Table#2]
Sometimes data value is not an object, but ... string.
In this case I get error. 
Please take a look at src/services/sortable-table.service.ts

`snapshot['forEach']((elem : database.DataSnapshot) => {
            const val = elem['val']();
            if (val) {
                **Object.defineProperty**(val, '$key', {
                    value: elem['key']
                });
                data.push(val);
            }
`

**Comment by IvanProdaiko94** [comment]
With [version 2.0.0](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/tree/2.0.0) you will manage refs, rather than data inside table
