### ISSUE TITLE
an empty space in the bottom of the table

### ISSUE THREAD

**Issue by iatalmid** [NodeArt/Angular-Firebase-Sortable-Table#4]
There is an an empty space in the bottom of the table.
I find the css
`.main-container {
    overflow-y: auto;
    height: calc(100% - 170px);
    position: relative;
}`

the style is encapsulated and It's too difficult to change this.
Can you fix the problem?

**Comment by IvanProdaiko94** [comment]
https://github.com/NodeArt/Angular-Firebase-Sortable-Table/issues/6#issuecomment-331658673
