### ISSUE TITLE
The manage to select data

### ISSUE THREAD

**Issue by iatalmid** [NodeArt/Angular-Firebase-Sortable-Table#5]
I couldn't find the way to pass firebase ref to component.
It would be better to have this possibility. In this way I can change the condition of select data.
Something like my own **orderBy**, **startedAt** and so on
For example I need orderByValue, but the component use orderByChild

**Comment by IvanProdaiko94** [comment]
https://github.com/NodeArt/Angular-Firebase-Sortable-Table/issues/2#issuecomment-331659198
