### ISSUE TITLE
Fixed position of header

### ISSUE THREAD

**Issue by iatalmid** [NodeArt/Angular-Firebase-Sortable-Table#6]
Can you get a possibility to define my own makeup?
For example the component use **table** tag and there is not way to define fixed position of header.

**Comment by IvanProdaiko94** [comment]
@iatalmid with [version 2.0.0](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/tree/2.0.0) all table will not have own styles. You'll be able to style inner content as you wish.
