### ISSUE TITLE
subscription 

### ISSUE THREAD

**Issue by iatalmid** [NodeArt/Angular-Firebase-Sortable-Table#7]
Google firebase can notify subscriber when table changed.
I couldn't find this ability in the component.
Table was changed but the component doesn't know about it and doesn't refresh data

**Comment by IvanProdaiko94** [comment]
With version 2.0.0 you will have this ability. 
```
<ngfb-sortable-table [tableConfig]="tableConfig" [currentPath]="path" (onEvent)="subscription()"></ngfb-sortable-table>
```
Thus you can notify app if smth has changed inside the table.
