### ISSUE TITLE
Какова структура файлов в Firebase?

### ISSUE THREAD

**Issue by 12evgen** [NodeArt/Angular-Firebase-Sortable-Table#9]
Привет! Не подскажешь, какова  структура файлов в database Firebase в демо? Хочу попробывать использовать твою таблицу, но не совсем понимаю как  ее подключить. Я так понимаю из за разной структуры (извини что issues на руском).

**Comment by IvanProdaiko94** [comment]
Привет. тебе стоит использовать [новую версию таблицы](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/tree/2.0.0). К сожалению на нее пока нет доки, но я работаю над этим. Вот [скрипт](
https://github.com/NodeArt/Angular-Firebase-Sortable-Table/blob/master/demo/generate_data.js
), который генерит структуру. Смотри демо [старая версия](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/tree/master/demo), [новая версия](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/tree/2.0.0/src)

**Comment by 12evgen** [comment]
Привет!
Спасибо за ответ!

Не совсем понял на счет как генерирует структру.  У меня уже есть созданная
в firebase база и я хочу вывести из строки Users (прикрепил картинку со
своей базы firebase), вставить эти данные в твою таблицу. Это возможно при
помощи твоей таблицы? Извини, может я глупый вопрос задаю) На счет скрипта,
и в целом всей твоей работы я изучу чуть позже.
 [image: https://ibb.co/mLCGFw]

31 октября 2017 г., 21:21 пользователь Ivan Prodaiko <
notifications@github.com> написал:

**Comment by IvanProdaiko94** [comment]
да. это возможно. ты должен написать компонент контейнер для таблицы и указать путь в конфиге. таблица сделает все остальное за тебя сама. [конфиг из демо новой версии](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/blob/2.0.0/src/app/ngfb-table-config.ts). Каждый ключ в `paths` - поле в базе. соответственно у тебя должно быть написанно `paths: { Users: config }`
[Использование](https://github.com/NodeArt/Angular-Firebase-Sortable-Table/blob/2.0.0/src/app/table-container/table-container.component.html#L26)

**Comment by 12evgen** [comment]
Странно, но я не смог запустить демо новой версии. 
Были две проблемы:
1) Ошибка импорта строки `import { MdSidenavModule, MdButtonModule, MdToolbarModule, MdIconModule, MdProgressBarModule } from '@angular/material';` 
Я исправил на:
`import { MatSidenavModule, MatButtonModule, MatToolbarModule, MatIconModule, MatProgressBarModule } from '@angular/material';`

2) Ошибка загрузки компонента `loadingComponent: LoadingComponent`. Я его просто удалил.

Но после этого все равно не грузиться демо. Ошибка консоли [Картинка](https://ibb.co/fr6avw)
Не подскажешь в чем может быть проблема?
